const PROP=PropertiesService.getScriptProperties(),ITER=10000;
function doPost(e){try{const q=JSON.parse(e.postData.contents);if(q.gatewayKey!==PROP.getProperty('GAS_SHARED_SECRET'))throw Error('Unauthorized gateway');const p=q.path,m=q.method,b=q.payload||{};if(p==='/v1/auth/login')return out_(login_(b));const u=session_((q.authorization||'').replace('Bearer ',''));if(p==='/v1/dashboard')return out_(dashboard_(u));if(p==='/v1/people'&&m==='GET')return out_(people_(u));if(p==='/v1/people'&&m==='POST')return out_(savePerson_(u,b));if(p==='/v1/claims'&&m==='GET')return out_({items:claims_(u)});if(p==='/v1/claims'&&m==='POST')return out_(createClaim_(u,b));if(/^\/v1\/claims\/[^/]+$/.test(p)&&m==='GET')return out_(claimDetail_(u,p.split('/')[3]));if(/^\/v1\/claims\/[^/]+\/approve$/.test(p)&&m==='POST')return out_(approve_(u,p.split('/')[3],b));if(p==='/v1/monthly'&&m==='GET')return out_({items:monthly_(u)});throw Error('Not found')}catch(x){return out_({error:true,message:x.message})}}
function login_(b){const r=rows_('ผู้ใช้').find(x=>String(x.username)===String(b.username)&&x.สถานะ!=='ระงับ');const valid=r&&(r.password_salt?safe_(r.password_hash,derive_(b.password,r.password_salt)):safe_(r.password_hash,legacy_(b.password)));if(!valid)throw Error('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง');const t=Utilities.getUuid();CacheService.getScriptCache().put('session:'+t,JSON.stringify({id:r.user_id,role:r.role,name:r['ชื่อ-สกุล']}),1800);audit_(r.username,'LOGIN','USER',r.user_id);return {token:t,expiresIn:1800,role:r.role,name:r['ชื่อ-สกุล']}}
function session_(t){const v=CacheService.getScriptCache().get('session:'+t);if(!v)throw Error('Session หมดอายุ');return JSON.parse(v)}function require_(u,r){if(!r.includes(u.role))throw Error('ไม่มีสิทธิ์ใช้งาน')}
function dashboard_(u){require_(u,['ADMIN','OFFICER','APPROVER']);const c=claims_(u);return {user:u,counts:{claims:c.length,draft:c.filter(x=>x.status==='ร่าง').length,pending:c.filter(x=>x.status==='รออนุมัติ').length,approved:c.filter(x=>x.status==='อนุมัติ').length},items:c}}
function people_(u){require_(u,['ADMIN','OFFICER','APPROVER']);return {items:rows_('บุคลากร').filter(x=>x.สถานะ!=='ยกเลิก').map(x=>({id:x.person_id,name:[x['คำนำหน้า'],x['ชื่อ'],x['นามสกุล']].join(''),position:x.ตำแหน่ง,level:x.ระดับ,unit:x['หน่วยบริการปัจจุบัน']}))}}
function savePerson_(u,b){require_(u,['ADMIN','OFFICER']);if(!b.firstName||!b.lastName||!b.position)throw Error('กรอกชื่อ นามสกุล และตำแหน่ง');const id='P'+Utilities.getUuid().slice(0,6).toUpperCase();sheet_('บุคลากร').appendRow([id,b.title||'',b.firstName,b.lastName,b.position,b.level||'',b.startDate||'',b.office||'',b.unit||'','','','','','','','','','','','','','','','ใช้งาน']);audit_(u.name,'CREATE','PERSON',id);return {ok:true,id:id}}
function claims_(u){require_(u,['ADMIN','OFFICER','APPROVER']);return rows_('คำขอเบิก').map(x=>({claimId:x.claim_id,personId:x.person_id,fiscalYear:x['ปีงบประมาณ'],month:x['เดือน'],type:x['ประเภทค่าตอบแทน'],amount:Number(x['จำนวนเงิน']||0),status:x.สถานะ,createdAt:x['สร้างเมื่อ']}))}
function createClaim_(u,b){require_(u,['ADMIN','OFFICER']);if(!b.personId||!b.fiscalYear||!b.month||!b.type||!b.rate||!b.months)throw Error('ข้อมูลคำขอไม่ครบ');const id='C'+b.fiscalYear+'-'+Utilities.getUuid().slice(0,5).toUpperCase(),total=Number(b.rate)*Number(b.months);sheet_('คำขอเบิก').appendRow([id,b.personId,b.fiscalYear,b.month,new Date(),b.type,b.rateId||'',b.startDate||'',b.endDate||'',Number(b.months),Number(b.rate),total,'ร่าง','','','','','','','','','','',b.note||'',new Date()]);audit_(u.name,'CREATE','CLAIM',id);return {ok:true,claimId:id}}
function claimDetail_(u,id){const x=rows_('คำขอเบิก').find(r=>r.claim_id===id);if(!x)throw Error('ไม่พบคำขอ');const p=rows_('บุคลากร').find(r=>r.person_id===x.person_id)||{};return {claim:x,person:p}}
function approve_(u,id,b){require_(u,['ADMIN','APPROVER']);const sh=sheet_('คำขอเบิก'),a=sh.getDataRange().getValues(),r=a.findIndex(x=>x[0]===id);if(r<1)throw Error('ไม่พบคำขอ');const status=b.approved?'อนุมัติ':'ไม่อนุมัติ';sh.getRange(r+1,13).setValue(status);sh.getRange(r+1,22).setValue(status);sh.getRange(r+1,23).setValue(b.note||'');audit_(u.name,status,'CLAIM',id);return {ok:true}}
function monthly_(u){require_(u,['ADMIN','OFFICER','APPROVER']);return rows_('ฉ11รายเดือน').map(x=>({id:x.monthly_id,personId:x.person_id,fiscalYear:x['ปีงบประมาณ'],month:x['เดือน'],amount:Number(x['จำนวนเงิน']||0),status:x.สถานะ}))}
function rows_(n){const a=sheet_(n).getDataRange().getValues(),h=a.shift();return a.map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]])))}function sheet_(n){const x=SpreadsheetApp.openById(PROP.getProperty('SPREADSHEET_ID')).getSheetByName(n);if(!x)throw Error('ไม่พบชีต '+n);return x}function derive_(password,salt){let value=salt+'|'+password;for(let i=0;i<10000;i++)value=Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8));return value}function legacy_(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,v,Utilities.Charset.UTF_8).map(x=>('0'+(x&255).toString(16)).slice(-2)).join('')}function safe_(a,b){if(!a||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}function audit_(u,a,e,id){sheet_('AuditLog').appendRow([new Date(),u,a,e,id,''])}function out_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}