const PROP=PropertiesService.getScriptProperties(),ITER=120000;
function doPost(e){try{const q=JSON.parse(e.postData.contents);if(q.gatewayKey!==PROP.getProperty('GAS_SHARED_SECRET'))throw Error('Unauthorized gateway');if(q.path==='/v1/auth/login')return out_(login_(q.payload||{}));const u=session_((q.authorization||'').replace('Bearer ',''));if(q.path==='/v1/claims'&&q.method==='GET')return out_({items:claims_(u)});if(q.path==='/v1/claims'&&q.method==='POST')return out_(createClaim_(u,q.payload||{}));if(q.path.match(/^\/v1\/claims\/[^/]+\/approve$/)&&q.method==='POST')return out_(approve_(u,q.path.split('/')[3],q.payload||{}));throw Error('Not found')}catch(x){return out_({error:true,message:x.message})}}
function login_(b){const sh=sheet_('ผู้ใช้'),h=sh.getDataRange().getValues(),r=h.slice(1).find(x=>String(x[1])===String(b.username)&&x[5]!=='ระงับ');if(!r||!r[7]||!secureEq_(r[2],derive_(b.password,r[7])))throw Error('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง');const t=Utilities.getUuid();CacheService.getScriptCache().put('session:'+t,JSON.stringify({id:r[0],role:r[4],name:r[3]}),1800);audit_(r[1],'LOGIN','USER',r[0]);return {token:t,expiresIn:1800,role:r[4]}}
function setPassword(username,password){const sh=sheet_('ผู้ใช้'),a=sh.getDataRange().getValues(),r=a.findIndex(x=>String(x[1])===String(username));if(r<1)throw Error('ไม่พบผู้ใช้');if(password.length<12)throw Error('รหัสผ่านต้องอย่างน้อย 12 ตัวอักษร');if(sh.getLastColumn()<8)sh.getRange(1,8).setValue('password_salt');const salt=Utilities.getUuid();sh.getRange(r+1,3).setValue(derive_(password,salt));sh.getRange(r+1,8).setValue(salt)}
function derive_(password,salt){let b=Utilities.computeHmacSha256Signature(password,salt);for(let i=1;i<ITER;i++)b=Utilities.computeHmacSha256Signature(b,password);return Utilities.base64Encode(b)}
function secureEq_(a,b){if(!a||!b||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function session_(t){const x=CacheService.getScriptCache().get('session:'+t);if(!x)throw Error('Session หมดอายุ');return JSON.parse(x)}function require_(u,roles){if(!roles.includes(u.role))throw Error('ไม่มีสิทธิ์ใช้งาน')}
function claims_(u){require_(u,['ADMIN','OFFICER','APPROVER']);const a=sheet_('คำขอเบิก').getDataRange().getValues();return a.slice(1).map(r=>({claimId:r[0],fiscalYear:r[1],month:r[2],amount:r[6],status:r[7]}))}
function createClaim_(u,b){require_(u,['ADMIN','OFFICER']);if(!b.personId||!b.month||!Number(b.amount))throw Error('ข้อมูลคำขอไม่ครบ');const id='CLM-'+Utilities.getUuid().slice(0,8).toUpperCase();sheet_('คำขอเบิก').appendRow([id,b.fiscalYear,b.month,b.personId,'',1,Number(b.amount),'รออนุมัติ',u.name,new Date(),'','','']);audit_(u.name,'CREATE','CLAIM',id);return {ok:true,claimId:id}}
function approve_(u,id,b){require_(u,['ADMIN','APPROVER']);const sh=sheet_('คำขอเบิก'),a=sh.getDataRange().getValues(),r=a.findIndex(x=>x[0]===id);if(r<1)throw Error('ไม่พบคำขอ');sh.getRange(r+1,8).setValue(b.approved===true?'อนุมัติ':'ไม่อนุมัติ');sh.getRange(r+1,12,1,2).setValues([[u.name,new Date()]]);audit_(u.name,'APPROVE','CLAIM',id);return {ok:true}}
function sheet_(n){return SpreadsheetApp.openById(PROP.getProperty('SPREADSHEET_ID')).getSheetByName(n)}function audit_(u,a,e,id){sheet_('AuditLog').appendRow([new Date(),u,a,e,id,''])}function out_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}